'use client';
import Link from 'next/link';
import { useEffect, useState, type FormEvent } from 'react';
import { confirmSignUp, getCurrentUser, signIn, signOut, signUp } from 'aws-amplify/auth';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '@/amplify/data/resource';
import ProductEditor from './product-editor';
import { isAmplifyConfigured } from '@/lib/amplify-client';

type User = { username: string; userId: string };
type StoreData = { slug: string; businessName: string; description: string; phone: string; whatsapp: string; city: string; address: string; openingHours: string; deliveryInfo: string; logoUrl: string; productsJson: string };
const empty: StoreData = { slug: '', businessName: '', description: '', phone: '', whatsapp: '', city: '', address: '', openingHours: '', deliveryInfo: '', logoUrl: '', productsJson: '[]' };
const client = () => generateClient<Schema>();
const slugify = (s: string) => s.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48);
const errText = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong. Please try again.';

export default function OwnerPortal() {
 const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState<'signup'|'signin'|'verify'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(isAmplifyConfigured)getCurrentUser().then(setUser).catch(()=>{});},[]);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('mode')==='signup')setMode('signup');},[]);
 async function authSubmit(e:FormEvent){e.preventDefault();setError('');setNote('');setBusy(true);try{
  if(mode==='signup'){const r=await signUp({username:email.trim().toLowerCase(),password,options:{userAttributes:{email:email.trim().toLowerCase()}}});if(!r.isSignUpComplete){setMode('verify');setNote('Check your email for a verification code.');}}
  else if(mode==='verify'){await confirmSignUp({username:email.trim().toLowerCase(),confirmationCode:code.trim()});setMode('signin');setNote('Email verified. Sign in to create your store.');}
  else {const r=await signIn({username:email.trim().toLowerCase(),password});if(r.isSignedIn)setUser(await getCurrentUser());else setNote('Complete email verification, then sign in again.');}
 }catch(e){setError(errText(e));}finally{setBusy(false);}}
 if(!isAmplifyConfigured)return <main className="portal"><header><Link className="brand" href="/">Market<span>Store</span>.ng</Link><Link href="/">Home</Link></header><section className="auth-card"><p className="eyebrow">Owner accounts</p><h1>Connect your AWS account</h1><p>Sign-up and store editing are ready in this project. Deploy the Amplify backend to your AWS account to create Cognito sign-in and the store database.</p><p className="notice">The existing S3 website is untouched. Follow the setup instructions in this project’s README.</p><Link className="button" href="/">Return home</Link></section></main>;
 if(user)return <Dashboard user={user} onSignOut={async()=>{await signOut();setUser(null);}}/>;
 return <main className="portal"><header><Link className="brand" href="/">Market<span>Store</span>.ng</Link><Link href="/">Home</Link></header><section className="auth-card"><p className="eyebrow">For store owners</p><h1>{mode==='signup'?'Create your owner account':mode==='verify'?'Verify your email':'Store owner sign in'}</h1><p>Sign in or create an account, then make your business page at marketstore.ng/your-business-name.</p>
 {mode!=='verify'&&<div className="tabs"><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('');setNote('');}}>Create account</button><button className={mode==='signin'?'active':''} onClick={()=>{setMode('signin');setError('');setNote('');}}>Sign in</button></div>}
 <form className="stack" onSubmit={authSubmit}><label>Email address<input type="email" autoComplete="email" required disabled={mode==='verify'} value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='verify'&&<label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='verify'&&<label>Verification code<input inputMode="numeric" autoComplete="one-time-code" required value={code} onChange={e=>setCode(e.target.value)}/></label>}<button className="button wide" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':mode==='verify'?'Verify email':'Sign in'}</button></form>
 {error&&<p className="message error" role="alert">{error}</p>}{note&&<p className="message" role="status">{note}</p>}
 </section></main>;
}

function Dashboard({user,onSignOut}:{user:User;onSignOut:()=>void}){
 const [store,setStore]=useState<StoreData|null>(null),[form,setForm]=useState<StoreData>(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{client().models.Store.list({authMode:'userPool'}).then(({data,errors})=>{if(errors?.length)throw Error(errors[0].message);const r=data?.[0];if(r){const value:StoreData={slug:r.slug,businessName:r.businessName,description:r.description||'',category:r.category||'',phone:r.phone||'',whatsapp:r.whatsapp||'',city:r.city||'',address:r.address||'',openingHours:r.openingHours||'',deliveryInfo:r.deliveryInfo||'',logoUrl:r.logoUrl||'',productsJson:r.productsJson||'[]'};setStore(value);setForm(value);}}).catch(e=>setError(errText(e))).finally(()=>setLoading(false));},[]);
 function change<K extends keyof StoreData>(k:K,v:StoreData[K]){setForm(f=>({...f,[k]:v}));}
 async function save(e:FormEvent){e.preventDefault();setError('');setNote('');setBusy(true);const slug=store?.slug||slugify(form.slug||form.businessName);if(!slug||['owner','dashboard','api','admin','search','create','businesses'].includes(slug)){setError('Choose a valid business name for your store link.');setBusy(false);return;}try{const input={...form,slug,businessName:form.businessName.trim()};const r=store?await client().models.Store.update(input,{authMode:'userPool'}):await client().models.Store.create(input,{authMode:'userPool'});if(r.errors?.length)throw Error(r.errors[0].message);if(!r.data)throw Error('The store could not be saved.');const value={...input,slug:r.data.slug};setStore(value);setForm(value);setNote('Your public store page is saved.');}catch(e){const m=errText(e);setError(/exist|conflict|conditional/i.test(m)?'That store link is taken. Try a more specific business name.':m);}finally{setBusy(false);}}
 if(loading)return <main className="dashboard"><p className="loading">Loading your account…</p></main>;
 return <main className="dashboard"><header><Link className="brand" href="/">Market<span>Store</span>.ng</Link><div className="account"><span>{user.username}</span><button onClick={onSignOut}>Sign out</button></div></header><section className="dash-title"><p className="eyebrow">Store owner dashboard</p><h1>{store?`Manage ${store.businessName}`:'Create your business page'}</h1><p>Set up the details customers will see on your MarketStore page.</p></section>
 <section className="dashboard-card"><h2>Business details</h2><form className="form-grid" onSubmit={save}><label>Business name<input required maxLength={80} value={form.businessName} onChange={e=>{change('businessName',e.target.value);if(!store)change('slug',slugify(e.target.value));}}/></label><label>Store link<input required disabled={Boolean(store)} value={store?.slug||form.slug} onChange={e=>change('slug',slugify(e.target.value))} placeholder="your-business-name"/><small>marketstore.ng/{store?.slug||form.slug||'your-business-name'}</small></label><label>Category<input value={form.category||''} onChange={e=>change('category',e.target.value)} placeholder="Food, fashion, electronics…"/></label><label>City<input value={form.city||''} onChange={e=>change('city',e.target.value)} placeholder="Lagos"/></label><label>Phone<input type="tel" value={form.phone||''} onChange={e=>change('phone',e.target.value)} placeholder="+234…"/></label><label>WhatsApp<input type="tel" value={form.whatsapp||''} onChange={e=>change('whatsapp',e.target.value)} placeholder="+234…"/></label><label className="full">About your business<textarea rows={3} value={form.description||''} onChange={e=>change('description',e.target.value)}/></label><label className="full">Address or area<input value={form.address||''} onChange={e=>change('address',e.target.value)}/></label><label>Opening hours<textarea rows={2} value={form.openingHours||''} onChange={e=>change('openingHours',e.target.value)}/></label><label>Delivery information<textarea rows={2} value={form.deliveryInfo||''} onChange={e=>change('deliveryInfo',e.target.value)}/></label><label className="full">Logo image link<input type="url" value={form.logoUrl||''} onChange={e=>change('logoUrl',e.target.value)} placeholder="https://…"/></label><button className="button wide full" disabled={busy}>{busy?'Saving…':store?'Save changes':'Create my page'}</button></form>{store&&<p className="notice">Your page: <Link href={'/'+store.slug} target="_blank">marketstore.ng/{store.slug} ↗</Link></p>}</section>
 {store&&<ProductEditor slug={store.slug} initial={store.productsJson||'[]'}/>} {error&&<p className="message error">{error}</p>}{note&&<p className="message">{note}</p>}</main>;
}