import Link from 'next/link';
export default function Home() {
  return <main>
    <header className="topbar"><Link className="brand" href="/">Market<span>Store</span>.ng</Link><nav className="nav-links"><a href="#how">How it works</a><a href="#features">What you get</a><Link href="/owner">Store owner log in</Link><Link className="button small" href="/owner?mode=signup">Create a page</Link></nav></header>
    <section className="hero"><div><p className="eyebrow">Nigeria’s small businesses, online</p><h1>Your business.<br/><span>Online.</span> Simply.</h1><p className="lead">Create a professional store page, add your products, and share one simple link with your customers.</p><div className="actions"><Link className="button" href="/owner?mode=signup">Create a page</Link><Link className="button outline" href="/owner">Store owner log in</Link></div><p className="small-note">Sign up with your email, then create your business page.</p></div>
      <aside className="preview"><div className="preview-title"><span className="avatar">A</span><div><b>Ada’s Kitchen</b><small>Lagos, Nigeria</small></div></div><p>Fresh meals made with care. Order directly on WhatsApp.</p><div className="preview-items"><div>🍲<b>Jollof Rice</b><small>₦4,500</small></div><div>🍛<b>Chicken & Rice</b><small>₦5,500</small></div></div><small className="slug">marketstore.ng/adas-kitchen</small></aside>
    </section>
    <section className="section" id="features"><p className="eyebrow">Your online storefront</p><h2>Everything customers need to choose you</h2><p className="muted">Show your business details, products and contact information in one shareable place.</p><div className="features"><article><b>01</b><h3>Your profile</h3><p>Business name, description, location, opening hours and delivery information.</p></article><article><b>02</b><h3>Your products</h3><p>Add product names, prices, descriptions and image links.</p></article><article><b>03</b><h3>Direct contact</h3><p>Customers can call or message you on WhatsApp to place an order.</p></article></div></section>
    <section className="section how" id="how"><p className="eyebrow">Simple to set up</p><h2>From account to store link</h2><ol><li><b>Create your owner account</b><span>Sign up with your email and verify it.</span></li><li><b>Add your business details</b><span>Choose your name and public store address.</span></li><li><b>Share your page</b><span>Your page is available at marketstore.ng/your-business-name.</span></li></ol></section>
    <footer><span>© 2026 MarketStore.ng</span><Link href="/owner">Store owner sign in</Link></footer>
  </main>;
}